baseurl: ""

title      : evo Copestone - Bond Origination & Home Loans Expert in Cape Town
email      : grant.butler@evogroup.co.za
description: Contact Grant Butler from evo Copestone to help you with your home loan. We are seasoned property professionals and specialize in mortgages and property finance with years of experience. Our experience ranges from sales to finance and out focus is bonds, homeloans and origination. evo Copestone is committed to excellent client service, building long-term relationships.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-XXX

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/evo copestone logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Home Loans

company: evo Copestone 

url: https://evohomeloans.co.za/bond-originator/cape-town/evo-copestone/ 

address: 75 Starfish, Ocean Tides Residential Estate, Big Bay, Cape Town, 7441
