baseurl: ""

title      : Mortgage4U - Bond Origination & Home Loans Experts
email      : grant.butler@evogroup.co.za
description: Get expert help with your home loan from Esme le Roux at Mortgage4U. Our experienced team specializes in mortgages, property finance, and bond origination, providing top-notch service and personalized solutions. Contact us today for professional guidance and build a long-term relationship with seasoned property professionals.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-XXX

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/mortage4u-logo.png


exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Home Loans

company: evo Copestone 

url: https://evohomeloans.co.za 

address: Residential Address